language: objective-c
osx_image: xcode7.3
before_install:
  - brew update
  - brew install opam
  - opam init
  - opam switch 4.02.3
  - eval `opam config env`
  - opam update
  - opam install -y depext
  - opam pin add -y merlin 'https://github.com/the-lambda-church/merlin.git#reason-0.0.1'
  - opam pin add -y merlin_extend 'https://github.com/let-def/merlin-extend.git#reason-0.0.1'
  - opam pin add -y --no-action reason 'https://github.com/facebook/reason.git#0.0.6'
install:
  - opam pin add -y --no-action infer .
  - opam depext infer
  - opam install -y infer
script:
  - infer --version
  - git diff --exit-code
